export default {
    products: [
      {
    "id": 201,
    "name": "Minus",
    "price": 207,
    "subCategoryId": 101,
    "categoryId": 1,
    "rate": 2.44,
    "brand": "Yashika",
    "review": 78,
    "content": "Product is good",
    "typeVariant": "D",
    "colorVariant": "5",
    "countInStock": 7,
    "image": "https://rukminim1.flixcart.com/image/460/552/jumzc7k0/sari/n/f/2/free-swati-dharmesh-enterprise-original-imaf2fz5ehjbywnu.jpeg?q=50"
  },
  {
    "id": 211,
    "name": "Minus",
    "price": 207,
    "subCategoryId": 101,
    "categoryId": 1,
    "rate": 2.44,
    "brand": "Yashika",
    "review": 78,
    "content": "Product is good",
    "typeVariant": "D",
    "colorVariant": "5",
    "countInStock": 7,
    "image": "https://rukminim1.flixcart.com/image/460/552/jumzc7k0/sari/n/f/2/free-swati-dharmesh-enterprise-original-imaf2fz5ehjbywnu.jpeg?q=50"
  },
  {
    "id": 202,
    "name": "Corporis",
    "price": 271,
    "subCategoryId": 101,
    "categoryId": 1,
    "brand": "Saara",
    "rate": 2.18,
    "content": "Nam incidunt blanditiis odio inventore. Nobis voluptatum quibusdam laboriosam a numquam. Delectus sequi ipsa possimus ratione repellendus quibusdam. Molestiae fuga laudantium natus dolorem.",
    "review": 67,
    "typeVariant": "A",
    "colorVariant": "4",
    "countInStock": 0,
    "image": "https://rukminim1.flixcart.com/image/460/552/k6fd47k0pkrrdj/sari/n/j/u/green-beige-red-yellow-1363sj505-1399sj503-siril-original-imafntm5uvc8jyg2.jpeg?q=50"
  },{
    "id": 203,
    "name": "Minus",
    "price": 295,
    "subCategoryId": 101,
    "categoryId": 1,
    "rate": 0.91,
    "brand":"Divastri",
    "content": "Quod reiciendis aspernatur ipsum cum debitis. Quisquam tempore doloremque quo ipsum ipsa tempora. Dignissimos qui ex ad facilis. Quo sequi recusandae eveniet autem ducimus nam.",
    "review": 116,
    "typeVariant": "E",
    "colorVariant": "2",
    "countInStock": 5,
    "image": "https://rukminim1.flixcart.com/image/460/552/k4d27ww0/sari/f/s/k/free-new-more-kanjivaram-fashion-anusuya-saree-original-imafgvemre4fcxy6.jpeg?q=50"
  },{
    "id": 204,
    "name": "Qui",
    "price": 280,
    "subCategoryId": 101,
    "categoryId": 1,
    "rate": 3.11,
    "content": "Occaecati dolore assumenda facilis error quaerat. Rem harum alias cum eum quam corporis. Esse numquam vero facilis labore.",
    "review": 78,
    "typeVariant": "D",
    "colorVariant": "3",
    "countInStock": 6,
    "image": "https://rukminim1.flixcart.com/image/460/552/k66sh3k0/sari/5/t/8/free-pari-24-maroon-dharm-enterprises-original-imafbb2hvzxqhs3x.jpeg?q=50"
  },{
    "id": 205,
    "name": "Blanditiis",
    "price": 138,
    "subCategoryId": 101,
    "categoryId": 1,
    "rate": 2.42,
    "content": "Reiciendis dolorum debitis occaecati assumenda totam ex. Ullam iure dolore excepturi unde in libero modi molestiae. Voluptate labore aliquid dignissimos omnis cum eligendi id. Sint repudiandae magni cum dolore itaque esse porro.",
    "review": 156,
    "typeVariant": "A",
    "colorVariant": "2",
    "countInStock": 10,
    "image": "https://rukminim1.flixcart.com/image/460/552/k3xcdjk0pkrrdj/sari/5/n/j/free-pink-hes950-1-hitesh-enterprise-hes950-1-original-imaf5tg4qhhf6xkx.jpeg?q=50"
  },{
    "id": 206,
    "name": "Est",
    "price": 296,
    "subCategoryId": 101,
    "categoryId": 1,
    "rate": 4.32,
    "content": "Aut consequatur fugit ut voluptates fugit numquam vero velit. Distinctio minima quo nesciunt maiores voluptatem dolorum. Doloribus quam nisi molestiae nostrum iure sint debitis.",
    "review": 107,
    "typeVariant": "E",
    "colorVariant": "3",
    "countInStock": 11,
    "image": "https://rukminim1.flixcart.com/image/460/552/k58hwnk0/sari/y/9/3/free-utsav-rust-marron-fine-wear-original-imafnyrbyhdq7fua.jpeg?q=50"
  },{
    "id": 207,
    "name": "Incidunt",
    "price": 183,
    "subCategoryId": 101,
    "categoryId": 1,
    "rate": 4.19,
    "content": "Nam aperiam rem atque ut eius molestiae ex omnis. Ex consequatur ipsam quaerat nam provident. Maiores quae consectetur soluta voluptatum. Ut ipsa est facilis.",
    "review": 174,
    "typeVariant": "E",
    "colorVariant": "3",
    "countInStock": 12,
    "image": "https://rukminim1.flixcart.com/image/460/552/k7gikcw0/sari/u/h/z/free-sdpl-nutella-red-yashika-unstitched-original-imafpzzjfwes8pzd.jpeg?q=50"
  },{
    "id": 208,
    "name": "Ratione",
    "price": 104,
    "subCategoryId": 101,
    "categoryId": 1,
    "rate": 4.64,
    "content": "Occaecati nam laudantium est quos. Fuga molestias facere consequatur sapiente cum reprehenderit quibusdam. Earum omnis ipsum numquam facilis perspiciatis architecto. Iste reiciendis minus distinctio corrupti eos. Excepturi ut sequi id blanditiis exercitationem.",
    "review": 104,
    "typeVariant": "B",
    "colorVariant": "3",
    "countInStock": 15,
    "image": "https://rukminim1.flixcart.com/image/460/552/k5e7o280/sari/f/v/v/free-woven-fashion-art-silk-saree-red-mossmoor-original-imafg7xpqhfswgxn.jpeg?q=50"
  },{
    "id": 209,
    "name": "Similique",
    "price": 262,
    "subCategoryId": 101,
    "categoryId": 1,
    "rate": 0.29,
    "content": "Autem blanditiis similique saepe excepturi at error. Fugit qui accusantium expedita. Illo similique suscipit sunt magni eos est.",
    "review": 44,
    "typeVariant": "C",
    "colorVariant": "3",
    "countInStock": 12,
    "image": "https://rukminim1.flixcart.com/image/460/552/jd1z9u80/sari/h/w/5/free-vjs366-2-v-j-fashion-original-imaewjjmx7bnkfzf.jpeg?q=50"
  }]}